### ISSUE TITLE
Setup 

### ISSUE THREAD

**Issue by thabti** [quran/quranicaudio-app#1]
- [ ] Find a Router/Navigator
- [ ] Redux/ Redux Saga
- [ ] Audio Player (supports mp3 via HTTP)
- [ ] Prototype a UI, maybe follow haramain app (https://itunes.apple.com/us/app/haramain/id1120580567?mt=8) @ahmedre please share any sketch or zeplin files

**Comment by mmahalwy** [comment]
yayyyy

**Comment by ahmedre** [comment]
i think Ahmad Galal may have his Sketch files for the design he gave me for both iOS and Android

**Comment by thabti** [comment]
@ahmedre I will reach out to him.
