### ISSUE TITLE
styled-components?

### ISSUE THREAD

**Issue by mmahalwy** [quran/quranicaudio-app#16]
Mind blown by this:
https://github.com/styled-components/styled-components#react-native

Uses:
https://github.com/styled-components/css-to-react-native

**Comment by thabti** [comment]
I think I am going to take the plunge and use it for this project. Thanks @mmahalwy

**Comment by mmahalwy** [comment]
It's awesome! I am using it for another project and in love. But SSR still hasnt been figured out though AFAIK :(
