### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by thabti** [quran/quranicaudio-app#2]
Some beautiful UI shared by AhmedGalal.

![1-home](https://cloud.githubusercontent.com/assets/2606228/23915237/68da8be6-08e0-11e7-87fe-3d182e9913ea.png)
![2-moods](https://cloud.githubusercontent.com/assets/2606228/23915234/68d9f7b2-08e0-11e7-814b-70b030e416f0.png)
![3-reciters](https://cloud.githubusercontent.com/assets/2606228/23915238/68daaed2-08e0-11e7-96b0-17c5f6136d00.png)
![4-track](https://cloud.githubusercontent.com/assets/2606228/23915235/68da1fee-08e0-11e7-84cc-26602647aceb.png)
![5-mini player](https://cloud.githubusercontent.com/assets/2606228/23915236/68daa1da-08e0-11e7-9cc6-4d8bc8323455.png)
![changing reciter](https://cloud.githubusercontent.com/assets/2606228/23915239/68e0b25a-08e0-11e7-8e2c-3b8393a83a2a.png)
![on aya click 2](https://cloud.githubusercontent.com/assets/2606228/23915243/68f1022c-08e0-11e7-9e01-f8ba0cf08e5a.png)
![on aya click](https://cloud.githubusercontent.com/assets/2606228/23915242/68efa58a-08e0-11e7-92a2-1d75f4c9c359.png)
![play queue](https://cloud.githubusercontent.com/assets/2606228/23915241/68ed9f4c-08e0-11e7-8fda-765d490d92db.png)
![track menu](https://cloud.githubusercontent.com/assets/2606228/23915240/68ed8d36-08e0-11e7-9523-fe7de8242698.png)

**Comment by mmahalwy** [comment]
oh lala! Love it!!!

**Comment by thabti** [comment]
More designs:
![home 2](https://cloud.githubusercontent.com/assets/2606228/24082904/17b1c05c-0cc5-11e7-8805-ebb0b65cc4d4.png)
![play](https://cloud.githubusercontent.com/assets/2606228/24082905/17c7a30e-0cc5-11e7-898a-836b84b9eede.png)
![reciters list](https://cloud.githubusercontent.com/assets/2606228/24082906/17d4be22-0cc5-11e7-990b-744af3442bf3.png)
