### ISSUE TITLE
Title is clipped

### ISSUE THREAD

**Issue by mohamede1945** [quran/quranicaudio-app#24]
![a86bc747-f551-40e2-ad4d-fd5bec0c7b5e](https://user-images.githubusercontent.com/5665498/45428973-5137bd80-b670-11e8-81dd-982a0c20bab1.jpeg)

**Comment by thabti** [comment]
This should be fixed once the layout has been changed to more aligned with this design:

![image](https://user-images.githubusercontent.com/2606228/45926692-4574b280-bf1e-11e8-984a-f26c7eff0fc0.png)
