### ISSUE TITLE
Close audio player dialog

### ISSUE THREAD

**Issue by mohamede1945** [quran/quranicaudio-app#25]
There's no way to stop the player. We can only pause it.

**Comment by thabti** [comment]
will look into this.

**Comment by thabti** [comment]
@mohamede1945 I had a look at Spotify and they don't stop the player. Why would you want to stop the player?
**Edit:**
I understand what you mean.  I will add option to close the player.

**Comment by mohamede1945** [comment]
👍

**Comment by mahmoudfelfel** [comment]
@mohamede1945 the player can be minimized already from that top right icon:
<img width="366" alt="screen shot 2018-10-11 at 9 33 13 pm" src="https://user-images.githubusercontent.com/3989750/46836090-1fc22700-cdc1-11e8-862d-909bccdd58a0.png">

Isn't that enough, or you mean something else?

**Comment by thabti** [comment]
If we truly want to remove the audio player as a whole we will have to re-think the UI. For now I will close this.
