### ISSUE TITLE
Filter are mistakenly carried over to the chapters list

### ISSUE THREAD

**Issue by mohamede1945** [quran/quranicaudio-app#27]
When setting a filter in reciters list and choose one e to open the filter is carried over to the next screen.
![cc050bd4-4de2-4344-827c-2418bf3ab9d4](https://user-images.githubusercontent.com/5665498/45429289-023e5800-b671-11e8-8a71-b34f1b649999.png)

**Comment by mmahalwy** [comment]
Rogers?! Are you living in Canada now?!

**Comment by mohamede1945** [comment]
Nice catch! 😀 Yes for over a year now in Ottawa and relocating this Friday to Toronto.

**Comment by mmahalwy** [comment]
@mohamede1945 wait what!!! amazing! Would love to grab coffee when I am back home visiting Toronto :)

**Comment by mohamede1945** [comment]
Yeah, that would be my pleasure :)

**Comment by thabti** [comment]
we removed filter on the surahs.
