### ISSUE TITLE
Audio Player

### ISSUE THREAD

**Issue by thabti** [quran/quranicaudio-app#4]
We need to find a decent Audio Player. Basic requirements:

- Can load MP3 files from HTTP
- Can preload
- Can save cache for offline playing (not a big deal)
- Play while out of the application

potential:

https://github.com/just-team/react-native-youtube-player
https://docs.expo.io/versions/v15.0.0/sdk/audio.html

**Comment by mahmoudfelfel** [comment]
I've started working on this, pls check this PR https://github.com/quran/quranicaudio-app/pull/21
The existing audio player doesn't support background play, and regarding offline download can be easily implemented using [this library](https://github.com/itinance/react-native-fs#downloadfileoptions-downloadfileoptions--jobid-number-promise-promisedownloadresult-)
